# URL for git clone
GIT_URL="-b asf-param-over-release https://github.com/agawande/NFD.git"

# Tag name or commit hash for checkout
GIT_VERSION=bc7cb95e727755361314b0243e557370db1b3a24

# Package name
NAME=nfd

# Package version
VERSION=0.5.1-73-gc65c9be

# PPA version
PPA_VERSION=2

include ../packaging.mk
